[color-theme]
name = "Wild pastel"

[color-theme.base]
white = "#b3b3b3"
black = "#14151a"
grey = "#3a454d"
blue = "#2d85b3"
red = "#b3322d"
yellow = "#b3a12d"
orange = "#b3692d"
green = "#9bb398"
purple = "#b32db3"
cyan = "#2db3b3"
magenta = "#8f86b3"

[color-theme.syntax]
attribute = "$blue"
builtinType = "$cyan"
comment = "$grey"
constant = "$cyan"
constructor = "$yellow"
embedded = "$blue"
enum = "$orange"
enum-member = "$red"
enumMember = "$blue"
escape = "$cyan"
field = "$orange"
function = "$red"
"function.method" = "$blue"
interface = "$green"
keyword = "$magenta"
"keyword.control" = "$purple"
label = "$grey"
method = "$orange"
number = "$yellow"
property = "$cyan"
"punctuation.delimiter" = "$red"
selfKeyword = "$red"
string = "$green"
"string.escape" = "$yellow"
struct = "$cyan"
structure = "$yellow"
symbol = "$yellow"
tag = ""
"text.reference" = ""
"text.title" = ""
"text.uri" = ""
type = "$yellow"
"type.builtin" = "$orange"
typeAlias = "$red"
variable = "$blue"
"variable.other.member" = "$blue"

[color-theme.ui]
"activity.background" = "$black"
"activity.current" = ""
"completion.background" = "$white"
"completion.current" = ""
"completion_lens.foreground" = "$cyan"
"editor.background" = "$black"
"editor.caret" = "$red"
"editor.current_line" = "#ffffff00"
"editor.dim" = "$grey"
"editor.drag_drop_background" = "#ffffff00"
"editor.drag_drop_tab_background" = "#ffffff00"
"editor.focus" = "$white"
"editor.foreground" = "$white"
"editor.indent_guide" = "$green"
"editor.link" = "$cyan"
"editor.selection" = "$red"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$white"
"error_lens.error.background" = ""
"error_lens.error.foreground" = ""
"error_lens.other.background" = ""
"error_lens.other.foreground" = ""
"error_lens.warning.background" = ""
"error_lens.warning.foreground" = ""
"hover.background" = "$black"
"inlay_hint.background" = "#ffffff00"
"inlay_hint.foreground" = "$grey"
"lapce.active_tab" = "#1e1e1e"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$grey"
"lapce.dropdown_shadow" = ""
"lapce.error" = ""
"lapce.icon.active" = "$orange"
"lapce.icon.inactive" = "$purple"
"lapce.inactive_tab" = "$red"
"lapce.plugin.author" = "$orange"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "$white"
"lapce.remote.connected" = "$green"
"lapce.remote.connecting" = "$orange"
"lapce.remote.disconnected" = "$red"
"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$orange"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$orange"
"lapce.tab.active.underline" = "$red"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "$orange"
"lapce.tab.separator" = "$grey"
"lapce.warn" = ""
"markdown.blockquote" = ""
"palette.background" = "$black"
"palette.current" = "$blue"
"palette.current.background" = "$orange"
"palette.current.foreground" = "$black"
"palette.foreground" = "$orange"
"panel.background" = "$black"
"panel.current" = "$black"
"panel.current.background" = "$black"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "$grey"
"panel.foreground" = "$grey"
"panel.foreground.dim" = "$grey"
"panel.hovered" = "#ffffff00"
"panel.hovered.background" = "#grey"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"
"source_control.added" = "#81b88b"
"source_control.modified" = "#e2c08d"
"source_control.removed" = "#c74e39"
"status.background" = "$black"
"status.foreground" = "$orange"
"status.modal.insert" = "$red"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.normal" = "$red"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$grey"
"status.modal.terminal" = "$red"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"
"status.modal.visual" = ""
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#666666"
"terminal.bright_blue" = "#3b8eea"
"terminal.bright_cyan" = "#29b8db"
"terminal.bright_green" = "#23d18b"
"terminal.bright_magenta" = "#d670d6"
"terminal.bright_red" = "#f14c4c"
"terminal.bright_white" = "#e5e5e5"
"terminal.bright_yellow" = "#f5f543"
"terminal.cursor" = "$green"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
list-line-height = 25
